"""add inventory orders payments analytics customers modules

Revision ID: 4301e0d1572d
Revises: 411ffd1ec70a
Create Date: 2026-07-06 18:44:36.836108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4301e0d1572d'
down_revision = '411ffd1ec70a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('address_text', sa.String(length=500), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_customer_id'), 'addresses', ['customer_id'], unique=False)
    op.add_column('customers', sa.Column('profile_image_url', sa.String(length=500), nullable=True))
    op.add_column('merchants', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.alter_column('merchants', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_merchants_google_id'), 'merchants', ['google_id'], unique=True)
    op.add_column('stores', sa.Column('logo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'logo_url')
    op.drop_index(op.f('ix_merchants_google_id'), table_name='merchants')
    op.alter_column('merchants', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('merchants', 'google_id')
    op.drop_column('customers', 'profile_image_url')
    op.drop_index(op.f('ix_addresses_customer_id'), table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###